# Generated by Django 5.2.5 on 2025-08-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/id_card', verbose_name='신분증 사진'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_id_card_uploaded',
            field=models.BooleanField(default=False, verbose_name='신분증 첨부 여부'),
        ),
    ]
