# Generated by Django 5.2.5 on 2025-08-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='conversation_style',
            field=models.CharField(blank=True, choices=[('A', '🤫 필요한 대화만'), ('B', '💬 자주 대화')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='important_points',
            field=models.CharField(blank=True, choices=[('A', '🧹 청결'), ('B', '🛌 생활 리듬'), ('C', '🧍 소통'), ('D', '🙋 배려심'), ('E', '🔏 사생활 존중')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='meal_preference',
            field=models.CharField(blank=True, choices=[('A', '\t🍽️ 함께 먹기 좋아해요'), ('B', '🍱 각자 먹기 선호해요')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='noise_level',
            field=models.CharField(blank=True, choices=[('A', '📺 하루 종일 틀어놓는 편이에요'), ('B', '🎶 특정 시간대만 들어요'), ('C', '🔇 거의 안 켜요')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pet_preference',
            field=models.CharField(blank=True, choices=[('A', '🐶 가능'), ('B', '🐱 불가능')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('A', '🌅 아침형'), ('B', '🌙 저녁형')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='smoking_preference',
            field=models.CharField(blank=True, choices=[('A', '🚬 예'), ('B', '🚭 아니오')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='space_sharing_preference',
            field=models.CharField(blank=True, choices=[('A', '자주 이용'), ('B', '필요할 때만'), ('C', '거의 이용 안 함')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weekend_preference',
            field=models.CharField(blank=True, choices=[('A', '🏠 집에서'), ('B', '🚶 외출')], max_length=1, null=True),
        ),
    ]
