# Generated by Django 5.2.5 on 2025-08-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='important_points',
            field=models.TextField(blank=True, null=True, verbose_name='생활 공간에서 가장 중요하게 생각하는 점'),
        ),
        migrations.AlterField(
            model_name='user',
            name='living_type',
            field=models.CharField(blank=True, choices=[('alone_female_senior', '혼자'), ('senior_couple', '시니어 부부'), ('grandchild', '손자')], max_length=30, null=True, verbose_name='동거 형태'),
        ),
    ]
