# Generated by Django 5.2.5 on 2025-08-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_id_card_image_user_is_id_card_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_land_register_uploaded',
            field=models.BooleanField(default=False, verbose_name='등기부등본 첨부 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='land_register',
            field=models.ImageField(blank=True, null=True, upload_to='users/land_register', verbose_name='등기부등본'),
        ),
    ]
