# Generated by Django 5.2.5 on 2025-08-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_conversation_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='living_type',
            field=models.CharField(blank=True, choices=[('alone_female_senior', '혼자'), ('senior_couple', '시니어 부부'), ('grandchild', '손자'), ('other', '기타')], max_length=30, null=True, verbose_name='동거 형태'),
        ),
        migrations.AddField(
            model_name='user',
            name='living_type_other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='기타 동거 형태'),
        ),
    ]
