# Generated by Django 5.2.5 on 2025-08-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_land_register_uploaded_user_land_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='important_points',
            field=models.CharField(choices=[('A', '🧹 청결'), ('B', '🛌 생활 리듬'), ('C', '🧍 소통'), ('D', '🙋 배려심'), ('E', '🔏 사생활 존중')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='meal_preference',
            field=models.CharField(choices=[('A', '\t🍽️ 함께 먹기 좋아해요'), ('B', '🍱 각자 먹기 선호해요')], default='A', max_length=1),
        ),
    ]
