# Generated by Django 5.2.5 on 2025-08-14 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='보증금')),
                ('rent_fee', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='월세')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('floor', models.CharField(max_length=50, verbose_name='층수')),
                ('area', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='면적(m²)')),
                ('utility_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='관리비')),
                ('can_short_term', models.BooleanField(default=False, verbose_name='단기 거주 가능 여부')),
                ('toilet_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='화장실 개수')),
                ('available_date', models.DateField(verbose_name='입주 가능일')),
                ('owner_living_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='거주 형태')),
                ('ai_analysis_result1', models.CharField(blank=True, max_length=200, null=True, verbose_name='AI 분석 결과 1')),
                ('ai_analysis_result2', models.CharField(blank=True, max_length=200, null=True, verbose_name='AI 분석 결과 2')),
                ('ai_matching_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='AI 매칭 점수')),
                ('options', models.JSONField(default=list, verbose_name='옵션')),
                ('security_facilities', models.JSONField(default=list, verbose_name='보안시설')),
                ('nearest_subway', models.CharField(blank=True, max_length=100, null=True, verbose_name='주변 지하철역')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '방',
                'verbose_name_plural': '방 목록',
            },
        ),
    ]
