# Generated by Django 5.2.5 on 2025-08-23 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='보증금')),
                ('rent_fee', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='월세')),
                ('floor', models.CharField(max_length=50, verbose_name='층수')),
                ('area', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='면적(m²)')),
                ('utility_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='관리비')),
                ('address_province', models.CharField(blank=True, max_length=50, null=True, verbose_name='주소(시/도)')),
                ('address_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='주소(시/군/구)')),
                ('address_district', models.CharField(blank=True, max_length=50, null=True, verbose_name='주소(읍/면/동)')),
                ('address_detailed', models.CharField(blank=True, max_length=50, null=True, verbose_name='상세주소(도로명/동/호)')),
                ('land_register_document', models.FileField(blank=True, null=True, upload_to='land_registers/', verbose_name='등기부 등본')),
                ('is_land_register_verified', models.BooleanField(default=False, verbose_name='등기부 등본 인증 여부')),
                ('can_short_term', models.BooleanField(default=False, verbose_name='단기 거주 가능 여부')),
                ('toilet_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='화장실 개수')),
                ('available_date', models.DateField(verbose_name='입주 가능일')),
                ('owner_living_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='거주 형태')),
                ('options', models.JSONField(default=list, verbose_name='생활 시설')),
                ('security_facilities', models.JSONField(default=list, verbose_name='보안 시설')),
                ('other_facilities', models.JSONField(default=list, verbose_name='기타 시설')),
                ('parking_available', models.BooleanField(default=False, verbose_name='주차 가능 여부')),
                ('pet_allowed', models.BooleanField(default=False, verbose_name='반려동물 가능 여부')),
                ('heating_type', models.CharField(blank=True, choices=[('INDIVIDUAL', '개별난방'), ('CENTRAL', '중앙난방'), ('DISTRICT', '지역난방')], max_length=20, null=True, verbose_name='난방 방식')),
                ('nearest_subway', models.CharField(blank=True, max_length=100, null=True, verbose_name='주변 지하철역')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '방',
                'verbose_name_plural': '방 목록',
            },
        ),
    ]
