# Generated by Django 5.2.5 on 2025-08-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='address_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='주소(시/군/구)'),
        ),
        migrations.AddField(
            model_name='room',
            name='address_district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='주소(읍/면/동)'),
        ),
        migrations.AddField(
            model_name='room',
            name='address_province',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='주소(시/도)'),
        ),
    ]
