# Generated by Django 5.2.5 on 2025-08-23 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='집 소개')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='room.room')),
            ],
            options={
                'verbose_name': '방 추가 정보',
                'verbose_name_plural': '방 추가 정보',
            },
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('COMMON', '공용 공간'), ('YOUTH', '청년 공간'), ('BATHROOM', '화장실')], max_length=20)),
                ('image', models.ImageField(upload_to='room_photos/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='room.room')),
            ],
            options={
                'verbose_name': '방 사진',
                'verbose_name_plural': '방 사진',
                'ordering': ['-created_at'],
            },
        ),
    ]
