# Generated by Django 5.2.5 on 2025-08-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', '입주 가능'), ('PENDING', '입주 요청 대기'), ('CONTRACTED', '계약 완료')], default='AVAILABLE', max_length=20, verbose_name='방 상태'),
        ),
    ]
