# Generated by Django 5.2.5 on 2025-08-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
    ]
