# Generated by Django 5.2.5 on 2025-08-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_address_city_room_address_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='address',
        ),
        migrations.RemoveField(
            model_name='room',
            name='ai_analysis_result1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='ai_analysis_result2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='ai_matching_score',
        ),
        migrations.AddField(
            model_name='room',
            name='address_detailed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='상세주소(도로명/동/호)'),
        ),
        migrations.AddField(
            model_name='room',
            name='heating_type',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', '개별난방'), ('CENTRAL', '중앙난방'), ('DISTRICT', '지역난방')], max_length=20, null=True, verbose_name='난방 방식'),
        ),
        migrations.AddField(
            model_name='room',
            name='other_facilities',
            field=models.JSONField(default=list, verbose_name='기타 시설'),
        ),
        migrations.AddField(
            model_name='room',
            name='parking_available',
            field=models.BooleanField(default=False, verbose_name='주차 가능 여부'),
        ),
        migrations.AddField(
            model_name='room',
            name='pet_allowed',
            field=models.BooleanField(default=False, verbose_name='반려동물 가능 여부'),
        ),
        migrations.AlterField(
            model_name='room',
            name='options',
            field=models.JSONField(default=list, verbose_name='생활 시설'),
        ),
        migrations.AlterField(
            model_name='room',
            name='security_facilities',
            field=models.JSONField(default=list, verbose_name='보안 시설'),
        ),
    ]
