# Generated by Django 5.2.5 on 2025-08-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_remove_room_address_remove_room_ai_analysis_result1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_land_register_verified',
            field=models.BooleanField(default=False, verbose_name='등기부 등본 인증 여부'),
        ),
        migrations.AddField(
            model_name='room',
            name='land_register_document',
            field=models.FileField(blank=True, null=True, upload_to='land_registers/', verbose_name='등기부 등본'),
        ),
    ]
