# Generated by Django 5.2.5 on 2025-08-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_document', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='임대차 계약서')),
                ('lived_period', models.CharField(choices=[('LESS_THAN_1_MONTH', '1개월 미만'), ('1_TO_3_MONTHS', '1개월 ~ 3개월'), ('3_TO_6_MONTHS', '3개월 ~ 6개월'), ('6_TO_12_MONTHS', '6개월 ~ 1년'), ('MORE_THAN_1_YEAR', '1년 이상')], default='LESS_THAN_1_MONTH', max_length=20, verbose_name='함께 지낸 기간')),
                ('satisfaction', models.CharField(choices=[('VERY_DISSATISFIED', '매우 불만족'), ('DISSATISFIED', '불만족'), ('NORMAL', '보통'), ('SATISFIED', '만족'), ('VERY_SATISFIED', '매우 만족')], default='NORMAL', max_length=20, verbose_name='전반적인 만족도')),
                ('good_points', models.TextField(blank=True, null=True, verbose_name='좋았던 점')),
                ('bad_points', models.TextField(blank=True, null=True, verbose_name='개선되었으면 하는 점')),
                ('re_living_hope', models.CharField(choices=[('YES', '네, 또 살고 싶어요 😊'), ('MAYBE', '상황에 따라 가능할 것 같아요'), ('NO', '아니요, 조금 힘들었어요')], default='MAYBE', max_length=20, verbose_name='재동거 희망 여부')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='익명으로 후기 작성')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
            options={
                'verbose_name': '후기',
                'verbose_name_plural': '후기 목록',
            },
        ),
    ]
