# Generated by Django 5.2.5 on 2025-08-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='익명 여부')),
                ('stay_period', models.CharField(max_length=50, verbose_name='거주 기간')),
                ('content', models.TextField(verbose_name='후기 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
            options={
                'verbose_name': '후기',
                'verbose_name_plural': '후기 목록',
            },
        ),
    ]
