# Generated by Django 5.2.5 on 2025-08-23 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL, verbose_name='후기 작성자'),
        ),
        migrations.AddField(
            model_name='review',
            name='target_senior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_received_senior', to=settings.AUTH_USER_MODEL, verbose_name='후기 대상(시니어)'),
        ),
        migrations.AddField(
            model_name='review',
            name='target_youth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_received_youth', to=settings.AUTH_USER_MODEL, verbose_name='후기 대상(청년)'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'room')},
        ),
    ]
