# Generated by Django 5.2.5 on 2025-08-21 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senior_reviews', to=settings.AUTH_USER_MODEL, verbose_name='후기 작성자(시니어)'),
        ),
        migrations.AddField(
            model_name='review',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_reviews', to='room.room', verbose_name='후기 대상 방'),
        ),
        migrations.AddField(
            model_name='review',
            name='youth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='youth_reviews', to=settings.AUTH_USER_MODEL, verbose_name='후기 대상(청년)'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'youth', 'room')},
        ),
    ]
