# Generated by Django 5.2.5 on 2025-08-24 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveInRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='연락처 확인 여부')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_in_requests_for_room', to='room.room')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_in_requests_as_youth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
