# Generated by Django 5.2.5 on 2025-08-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveinrequest',
            name='is_contacted',
            field=models.BooleanField(default=False, verbose_name='연락처 확인 여부'),
        ),
    ]
