# Generated by Django 5.2.5 on 2025-08-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_alter_moveinrequest_is_contacted'),
        ('matching', '0003_initial'),
    ]

    operations = [
    ]
